# Script entregable

In [3]:
import numpy as np

### a) Creación de vectores: se crea el arreglo con np.array

In [17]:

a=np.array([3.1,1, -0.5, -3.2, 6])
b=np.array([1, 3, 2.2, 5.1, 1])

### b) Multiplicación escalar 

In [25]:
a * b
#Nota: para multiplicar dos matrices, deben tener el mismo número de columnas que filas de la segunda.
#Las dimensiones columna-fila, deben coincidir. 
#El resultado es una matriz con el mismo número de filas de la primera y mismo número de columnas de la segunda


array([  3.1 ,   3.  ,  -1.1 , -16.32,   6.  ])

## c) Producto punto

In [23]:
np.dot(a,b)

-5.320000000000002

## d) Construcción de matriz

## e) Transpuesta de la matriz 

Se utiliza el método matriz.T

## f) Función de los comandos

### ones: 
El comando numpy.ones, crea una matriz cuyos elementos tendrán el valor 1.

### round:
Redondea uniformemente los números contenidos en la matriz de manera uniforme

### ceil:
Opera la matriz de manera que calcula el entero más cercano hacia arriba de cada uno de los elementos que la conforman.

### floor: 
Opera la matriz de manera que calcula el entero más cercano hacia abajo de cada uno de los elementos que la conforman.


### Ejemplificación

In [27]:
#ones 
matriz = np.ones((2,13), dtype='float')

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
#round 
array = np.random.rand(2,3)
array.round()

[[0. 1. 1.]
 [1. 0. 0.]]


In [48]:
#ceil
np.ceil(array)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [50]:
#floor
np.floor(array)

array([[0., 0., 0.],
       [0., 0., 0.]])