In [10]:
import numpy as np 
a = np.array([3.1,1, -0.5, -3.2, 6])
b = np.array([1, 3, 2.2, 5.1, 1]) #punto a
escalar= ((a @ b))
print ( escalar,  "es el resultado de producto escalar de los dos vectores " )#punto b, usar la función u.dot(v)
print (np.dot(a, b))
punto_punto= (a*b)
print ("la multiplicacion punto a punto es " , punto_punto ) # punto c


-5.320000000000002 es el resultado de producto escalar de los dos vectores 
-5.320000000000002
la multiplicacion punto a punto es  [  3.1    3.    -1.1  -16.32   6.  ]


In [18]:
import numpy as np 
A = np.array ([[2,-1,-3],
               [4,1.5,-2.5],
               [7.3,-0.9,0.2]])
print (A) #punto d
print ("la matriz traspuesta de A es: "
       , A.T) # punto e

[[ 2.  -1.  -3. ]
 [ 4.   1.5 -2.5]
 [ 7.3 -0.9  0.2]]
la matriz traspuesta de A es:  [[ 2.   4.   7.3]
 [-1.   1.5 -0.9]
 [-3.  -2.5  0.2]]


In [40]:
import numpy as np
a = np.array([-1.7, 1.78, -0.2, 0.89, 2.5, 4.7, -5.99])
print ("ones")
print(np.ones((3, 3))) # punto f ones, matriz de unos
print ("round")
print (np.round(a,1)) # punto f round, redodea con una sola decimal
print ("ceil")
print (np.ceil(a)) # punto f ceil, del escalar x es el entero más pequeño i
print ("floor")
print (np.floor(a))# punto f floor, del escalar x es el entero más grande

ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
round
[-1.7  1.8 -0.2  0.9  2.5  4.7 -6. ]
ceil
[-1.  2. -0.  1.  3.  5. -5.]
floor
[-2.  1. -1.  0.  2.  4. -6.]


In [67]:
import numpy as np 
A = np.array ([[2,-1,-3],
               [4,1.5,-2.5],
               [7.3,-0.9,0.2]])
print(A)
acceder = A[0,2]  # punto g, Acceso al elemento de la fila 1 columna 3, empieza a contar desde 0
print ("el elemento ubicado en la primer fila y tercera columna es : ",acceder)
segundafila= A[1,:] # punto h, acceder a la segunda fila
print (segundafila)
dimensiones = A.shape # punto j, como conocer las dimensiones de una matriz
print (" Las dimenciones de la matriz A es : ",dimensiones)


[[ 2.  -1.  -3. ]
 [ 4.   1.5 -2.5]
 [ 7.3 -0.9  0.2]]
el elemento ubicado en la primer fila y tercera columna es :  -3.0
[ 4.   1.5 -2.5]
 Las dimenciones de la matriz A es :  (3, 3)


In [82]:
#punto j 
import numpy as np 
import random

def funcionseno():
    n=random.randint(0,100) #random para generar numero aleatorio entre 0 y 100
    y= np.sin(np.pi*0.12*n) #se toma el numero aleatorio en la funcion 
    return n,y # devuelve resultados
    
    
valor,final= funcionseno()
print( "para  el valor : ", valor,"el resultado de y es: ", final)


para  el valor :  50 el resultado de y es:  -7.347880794884119e-16


In [81]:
#punto k
import numpy as np 
import random

def funcioncoseno():
    n=random.randint(0,100)
    y2= np.cos((2*np.pi)*0.03*n)
    return n,y2
    
    
valor,final= funcioncoseno()
print( "para  el valor : ", valor,"el resultado de y es: ", final)


para  el valor :  11 el resultado de y es:  -0.48175367410171505


In [88]:
#punto l 
import numpy as np 
import random

def funcioncoseno():
    n=random.randint(0,100)
    y= np.sin(np.pi*0.12*n)
    yd= np.cos((2*np.pi)*0.03*n)
    sn= y+yd
    tn=y*yd 
    
    return n,y, yd, sn, tn
    
    
valor,primera,segunda,tercera,cuarta= funcioncoseno()
print( "para valor aleatorio: ", valor, '\n'
      "el resultado de la primera señal  seno es: ", primera,'\n'
      "el de la segunda coseno: ", segunda,'\n'
      " el de la tercera o suma de las dos primeras:" ,tercera, '\n'
      " y el de la cuarta es o producto de las dos primeras: ", cuarta)


para valor aleatorio:  14 
el resultado de la primera señal  seno es:  -0.8443279255020155 
el de la segunda coseno:  -0.8763066800438635 
 el de la tercera o suma de las dos primeras: -1.720634605545879 
 y el de la cuarta es o producto de las dos primeras:  0.7398902012649937
