In [10]:
import numpy as np 
a = np.array([3.1,1, -0.5, -3.2, 6])
b = np.array([1, 3, 2.2, 5.1, 1]) #punto a
escalar= ((a @ b))
print ( escalar,  "es el resultado de producto escalar de los dos vectores " )#punto b, usar la función u.dot(v)
print (np.dot(a, b))
punto_punto= (a*b)
print ("la multiplicacion punto a punto es " , punto_punto ) # punto c


-5.320000000000002 es el resultado de producto escalar de los dos vectores 
-5.320000000000002
la multiplicacion punto a punto es  [  3.1    3.    -1.1  -16.32   6.  ]


In [18]:
import numpy as np 
A = np.array ([[2,-1,-3],
               [4,1.5,-2.5],
               [7.3,-0.9,0.2]])
print (A) #punto d
print ("la matriz traspuesta de A es: "
       , A.T) # punto e

[[ 2.  -1.  -3. ]
 [ 4.   1.5 -2.5]
 [ 7.3 -0.9  0.2]]
la matriz traspuesta de A es:  [[ 2.   4.   7.3]
 [-1.   1.5 -0.9]
 [-3.  -2.5  0.2]]


In [40]:
import numpy as np
a = np.array([-1.7, 1.78, -0.2, 0.89, 2.5, 4.7, -5.99])
print ("ones")
print(np.ones((3, 3))) # punto f ones, matriz de unos
print ("round")
print (np.round(a,1)) # punto f round, redodea con una sola decimal
print ("ceil")
print (np.ceil(a)) # punto f ceil, del escalar x es el entero más pequeño i
print ("floor")
print (np.floor(a))# punto f floor, del escalar x es el entero más grande

ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
round
[-1.7  1.8 -0.2  0.9  2.5  4.7 -6. ]
ceil
[-1.  2. -0.  1.  3.  5. -5.]
floor
[-2.  1. -1.  0.  2.  4. -6.]
